planning_scene_monitor_options:
  name: "planning_scene_monitor"
  robot_description: "robot_description"
  joint_state_topic: "/joint_states"
  attached_collision_object_topic: "/moveit_cpp/planning_scene_monitor"
  publish_planning_scene_topic: "/moveit_cpp/publish_planning_scene"
  monitored_planning_scene_topic: "/moveit_cpp/monitored_planning_scene"
  wait_for_initial_state_timeout: 10.0

planning_pipelines:
  #namespace: "moveit_cpp"  # optional, default is ~
  pipeline_names: ["ompl", "pilz_industrial_motion_planner", "chomp"]

ompl:
  planning_plugin: ompl_interface/OMPLPlanner
  planning_plugins:
    - ompl_interface/OMPLPlanner
  request_adapters:
    - default_planning_request_adapters/ResolveConstraintFrames
    - default_planning_request_adapters/ValidateWorkspaceBounds
    - default_planning_request_adapters/CheckStartStateBounds
    - default_planning_request_adapters/CheckStartStateCollision
  response_adapters:
    - default_planning_response_adapters/AddTimeOptimalParameterization
    - default_planning_response_adapters/ValidateSolution
    - default_planning_response_adapters/DisplayMotionPath
  planner_configs:
    PRMstarkConfigDefault:
      type: geometric::PRMstar
    RRTConnectkConfigDefault:
      type: geometric::RRTConnect
  ur_arm:
    planner_configs:
      - PRMstarkConfigDefault
      - RRTConnectkConfigDefault

pilz_industrial_motion_planner:
  planning_plugin: pilz_industrial_motion_planner/CommandPlanner
  planning_plugins:
    - pilz_industrial_motion_planner/CommandPlanner
  request_adapters:
    - default_planning_request_adapters/ResolveConstraintFrames
  response_adapters:
    - default_planning_response_adapters/ValidateSolution
    - default_planning_response_adapters/DisplayMotionPath

chomp:
  planning_plugin: chomp_interface/CHOMPPlanner
  planning_plugins:
    - chomp_interface/CHOMPPlanner
  request_adapters:
    - default_planning_request_adapters/ResolveConstraintFrames
    - default_planning_request_adapters/ValidateWorkspaceBounds
    - default_planning_request_adapters/CheckStartStateBounds
    - default_planning_request_adapters/CheckStartStateCollision
  response_adapters:
    - default_planning_response_adapters/AddTimeOptimalParameterization
    - default_planning_response_adapters/ValidateSolution
    - default_planning_response_adapters/DisplayMotionPath

# Default plan request (used by rec_bot_control)
plan_request_params:
  planning_attempts: 10
  planning_pipeline: ompl
  planner_id: "RRTConnectkConfigDefault"
  max_velocity_scaling_factor: 0.3
  max_acceleration_scaling_factor: 0.3

# Named plan request configs for each planner
ompl_rrtc:
  plan_request_params:
    planning_attempts: 10
    planning_pipeline: ompl
    planner_id: "RRTConnectkConfigDefault"
    max_velocity_scaling_factor: 0.3
    max_acceleration_scaling_factor: 0.3
    planning_time: 5.0

pilz_ptp:
  plan_request_params:
    planning_attempts: 1
    planning_pipeline: pilz_industrial_motion_planner
    planner_id: "PTP"
    max_velocity_scaling_factor: 0.3
    max_acceleration_scaling_factor: 0.3
    planning_time: 0.8

pilz_lin:
  plan_request_params:
    planning_attempts: 1
    planning_pipeline: pilz_industrial_motion_planner
    planner_id: "LIN"
    max_velocity_scaling_factor: 0.3
    max_acceleration_scaling_factor: 0.3
    planning_time: 0.8

chomp_planner:
  plan_request_params:
    planning_attempts: 1
    planning_pipeline: chomp
    max_velocity_scaling_factor: 0.3
    max_acceleration_scaling_factor: 0.3
    planning_time: 1.5
